services:
  db: 
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=men
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=men_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: