# Generated by Django 4.2.7 on 2023-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
