# Generated by Django 4.2.7 on 2023-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_men_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
