# Generated by Django 4.2.7 on 2024-02-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': 'Супругу', 'verbose_name_plural': 'Супруги'},
        ),
    ]
