# Generated by Django 4.2.7 on 2024-10-11 15:18

import autoslug.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_alter_tagpost_options_alter_wife_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Слишком короткий слаг.'), django.core.validators.MaxLengthValidator(100)], verbose_name='URL'),
        ),
    ]
