# Generated by Django 4.2.7 on 2023-11-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_category_men_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'ordering': ['time_create']},
        ),
        migrations.RemoveIndex(
            model_name='men',
            name='men_men_time_cr_642e6a_idx',
        ),
        migrations.AlterField(
            model_name='men',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='men.category'),
        ),
        migrations.AddIndex(
            model_name='men',
            index=models.Index(fields=['time_create'], name='men_men_time_cr_96f2b0_idx'),
        ),
    ]
