# Generated by Django 4.2.7 on 2023-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0008_wife_men_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
