# Generated by Django 4.2.7 on 2024-01-11 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0010_alter_category_options_alter_men_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Слишком короткий слаг.'), django.core.validators.MaxLengthValidator(100)], verbose_name='URL'),
        ),
    ]
