# Generated by Django 4.2.7 on 2024-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0012_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
